### ISSUE TITLE
Check this error

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CanvasApp#3] opened 2018-11-24 16:30 UTC
CloudVM : [ERROR] checkForChangesInBotCode -> err.message = newUserBot is not defined

![image](https://user-images.githubusercontent.com/34651529/48970608-e51cf280-efec-11e8-922d-c46d5daa1e2a.png)

**Comment by Luis-Fernando-Molina** [comment] 2019-02-13 19:55
Many things have changed since this error was reported. No way to reproduce it today. Closing it to clean up the issue list.

**Closed by Luis-Fernando-Molina** 2019-02-13 19:55 UTC
